org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx4g
org.gradle.parallel=true
org.gradle.configureondemand=true
kotlin.code.style=official

android.useAndroidX=true
android.enableJetifier=true

org.gradle.caching=true
kotlin.parallel.tasks.in.project=true

# Hermes + New Architecture
enableHermes=true
newArchEnabled=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Kotlin configuration
kotlin.jvm.target=17
